version: "2"

services:
  config:
    image: thegene/gallery-manifests
    volumes:
      - config:/config
  harrison-build:
    image: thegene/gallery
    environment:
      - GALLERY_ENV=production
      - GALLERY=harrison_newborn
    depends_on:
      - config
    volumes_from:
      - config
    volumes:
      - harrison-build:/build
  harrison:
    image: thegene/gallery-server
    depends_on:
      - harrison-build
    volumes_from:
      - harrison-build
    ports:
      - "80"
  wedding-build:
    image: thegene/gallery
    environment:
      - GALLERY_ENV=production
      - GALLERY=wedding
    depends_on:
      - config
    volumes_from:
      - config
    volumes:
      - wedding:/build
  wedding:
    image: thegene/gallery-server
    depends_on:
      - wedding-build
    volumes_from:
      - wedding-build
    ports:
      - "80"

volumes:
  wedding:
  harrison-build:
  config:
